import streamlit as st
import os

st.set_page_config(
    page_title="Download Reports",
    layout="wide"
)

st.title("📥 Download Reports")

st.markdown(
    """
    Download forecasting reports generated by different models.
    """
)

report_files = {

    "Moving Average":
        "outputs/moving_average_results.xlsx",

    "SES":
        "outputs/ses_results.xlsx",

    "Holt":
        "outputs/holt_results.xlsx",

    "ARIMA":
        "outputs/arima_results.xlsx",

    "Recursive Linear Regression":
        "outputs/recursive_linear_regression_results.xlsx"

}

for report_name, file_path in report_files.items():

    st.markdown("---")

    st.subheader(report_name)

    if os.path.exists(file_path):

        with open(file_path, "rb") as file:

            st.download_button(
                label=f"Download {report_name}",
                data=file,
                file_name=os.path.basename(file_path),
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

    else:

        st.error(
            f"File not found: {file_path}"
        )